name: CI

on: pull_request

jobs:
  build:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        os:
          - iOS
          - macOS
          - watchOS
          - tvOS
    steps:
    - uses: actions/checkout@v4
    - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
    - run: xcodebuild -scheme AttributedText -destination 'generic/platform=${{ matrix.os }}' build
  lint:
    runs-on: ubuntu-24.04-arm
    container: swift:latest
    steps:
      - uses: actions/checkout@v4
      - run: swift format lint -r -p -s .
